### ISSUE TITLE
Unread messages bubble in main view remains after visiting room and viewing all new messages using experimental setting `Client-generated unread counts`

### ISSUE THREAD

**Issue by foss-** [SchildiChat/schildichat-android-next#45] opened 2024-12-30 11:56 UTC
Not reproduced in Element X 0.7.5 / 0.7.6

**Describe the bug**
Unread messages bubble in main view remains after visiting room and viewing all new messages.

**To Reproduce**
1. have at least 1 unread message in a room
2. this is indicated via a green bubble with the number of unread messages on the right side of the room in the room list
3. open room and read all messages, scroll up / down to ensure app knows all messages are seen
4. leave room
5. in main view the room still has `n` unread messages showing in the unread messages bubble indicator

**Expected behavior**
After visiting a room with unread messages, the unread indicator should vanish.

**Smartphone (please complete the following information):**
 - Device: Not devices related as this was reproduced on several devices running Android 15 + 13.

**Additional context**
 - App version: 0.7.5
 - Store: F-Droid
 - Homeserver: matrix.org
 - Related experimental/labs settings: yes, had Client-generated unread counts enabled, disabled this setting and the unread bubbles vanished as expected

**Upstream relevance**
 - Does this issue exist in Element X Android? no

**Comment by SpiritCroc** [comment] 2024-12-30 12:00
Have you tweaked any other experimental settings? I.e. can you provide a screenshot of Settings / Turtle Tweaks / Developer Options / User-changed settings?

**Comment by foss-** [comment] 2024-12-30 13:18
Disabling both top options resolved the issue. I am fine with that, but still wanted to let you know about the problematic option not behaving as expected.
![1](https://github.com/user-attachments/assets/c50fc107-0c18-4dc8-8989-47c057355fea)

**Comment by SpiritCroc** [comment] 2024-12-30 13:36
I doubt these options resolve the issue. Disabling client-generated unread counts will just break all unread counts if the server doesn't provide them properly, which all recent synapses do, just like matrix.org.

The issue is that you have "Keep read marker and receipt in sync" enabled. It is known that this breaks marking rooms as read automatically. Maybe I should hide them even deeper than experimental settings, since I wouldn't recommend any user to turn this setting on, as it requires a lot of background knowledge to navigate around.

**Comment by SpiritCroc** [comment] 2024-12-30 15:37
Rooms not getting marked as read automatically is known and expected while "Keep read marker and receipt in sync" is enabled. I added some more disclaimers and moved the setting into the danger zone in https://github.com/SchildiChat/schildichat-android-next/commit/f4afb06dd8f946b5684cde7f528262bac902c29b .

**Closed by SpiritCroc** 2024-12-30 15:37 UTC
